const TipeMembershipActionTypes = {
  FETCH_ALL_TIPE_MEMBERSHIP_START: 'FETCH_ALL_TIPE_MEMBERSHIP_START',
  FETCH_ALL_TIPE_MEMBERSHIP_SUCCESS: 'FETCH_ALL_TIPE_MEMBERSHIP_SUCCESS',
  FETCH_ALL_TIPE_MEMBERSHIP_FAILURE: 'FETCH_ALL_TIPE_MEMBERSHIP_FAILURE',
}

export default TipeMembershipActionTypes
