export const AdminActionTypes = {
  SET_CURRENT_ADMIN_START: 'SET_CURRENT_ADMIN_START',
  SET_CURRENT_ADMIN_SUCCESS: 'SET_CURRENT_ADMIN_SUCCESS',
  SET_CURRENT_ADMIN_FAILURE: 'SET_CURRENT_ADMIN_FAILURE',
  LOGOUT_CURRENT_ADMIN: 'LOGOUT_CURRENT_ADMIN',
}
