const MemberActionTypes = {
  LOAD_ALL_MEMBER_START: 'LOAD_ALL_MEMBER_START',
  LOAD_ALL_MEMBER_SUCCESS: 'LOAD_ALL_MEMBER_SUCCESS',
  LOAD_ALL_MEMBER_FAILURE: 'LOAD_ALL_MEMBER_FAILURE',
}

export default MemberActionTypes
