const MembershipActionTypes = {
  FETCH_ALL_MEMBERSHIP_START: 'FETCH_ALL_MEMBERSHIP_START',
  FETCH_ALL_MEMBERSHIP_SUCCESS: 'FETCH_ALL_MEMBERSHIP_SUCCESS',
  FETCH_ALL_MEMBERSHIP_FAILURE: 'FETCH_ALL_MEMBERSHIP_FAILURE',
}

export default MembershipActionTypes
