const MembershipActionTypes = {
  LOAD_ALL_MEMBERSHIP_START: 'LOAD_ALL_MEMBERSHIP_START',
  LOAD_ALL_MEMBERSHIP_SUCCESS: 'LOAD_ALL_MEMBERSHIP_SUCCESS',
  LOAD_ALL_MEMBERSHIP_FAILURE: 'LOAD_ALL_MEMBERSHIP_FAILURE',
}

export default MembershipActionTypes
